# Alternight theme for Helix
# Author: Mauricio Paternina<hi@mau.sh>
# Upstream: https://github.com/alternight-theme/helix
# Contributing
#   Please submit your changes to the upstream above.
#   The Alternight team will update the repo, including you as a co-author.

"ui.background" = { bg = "darknet" }
"ui.background.separator" = { bg = "darknet" }

"ui.cursor" = { bg = "tech_hazard", fg = "darknet", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "tech_hazard", fg = "darknet", modifiers = ["bold"] }
"ui.cursor.primary" = { bg = "tech_hazard", fg = "darknet" }

# "ui.cursorline.primary" = { bg = "test_red" }

"ui.help" = { bg = "dreamware", fg = "darknet" }

"ui.linenr" = "low_signal"
"ui.linenr.selected" = { fg = "ghost_print" }

"ui.menu" = { bg = "darknet_softwired", fg = "ghost_print" }
"ui.menu.selected" = { bg = "ghost_print", fg = "darknet" }

"ui.popup" = { bg = "darknet_echoed", fg = "ghost_print" }

# OPTIMIZE: Find ideal background color
"ui.selection" = { fg = "darknet", bg = "low_signal" }

"ui.statusline" = { fg = "ghost_print", bg = "darknet_softwired" }
"ui.statusline.inactive" = { bg = "#D8959A", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "tech_hazard", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.normal" = { bg = "glitch_blossom", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "stackwave", fg = "darknet", modifiers = ["bold"] }

"ui.text" = "ghost_print"

"ui.virtual.indent-guide" = "darknet_softwired"

"ui.window" = { bg = "test_red" }

# TODO: "diagnostic.error" = { fg = "#E85462", bg = "#FADBDE", underline = { color = "#E85462", style = "curl" } }

"diff.minus" = "redshift"
"diff.plus" = "sys_ready"

error = { fg = "#E85462", bg = "#FADBDE", underline = { color = "#E85462", style = "curl" } }
# error = "synthetic_bleed"
hint = "coolbit"
info = "stackwave"
warning = "solarbyte"

# Syntax
# TODO: attribute

comment = "low_signal"
# TODO: "comment.block.documentation"

constant = "solarbyte"
# TODO: "constant.builtin"
"constant.character" = "neuroshade"
"constant.character.escape" = "mintcore"
# "constant.numeric" = "solarbyte"
"constant.numeric" = "neon_orchid"

# TODO: constructor

function = "cachelight"
"function.builtin" = { fg = "cachelight", modifiers = ["bold"] }
# TODO: "function.macro"
# TODO: "function.special"

# keyword = { fg = "dreamware", modifiers = ["italic"] }
keyword = "dreamware"
"keyword.directive" = "dreamware_overclocked"

markup = "dreamware_overclocked"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "pixelated_petal"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "stackwave"
"markup.link.url" = "coldboot"
"markup.quote" = { fg = "pixelated_petal", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

namespace = { fg = "dreamware_echoed", modifiers = ["bold"] }

string = "sys_ready"
"string.regexp" = "neon_orchid"
"string.special" = "sys_ready_echoed"

type = "ambertrace"
# TODO: Find alternative
# "type.builtin" = "ambertrace_overclocked"
# "type.builtin" = "neon_orchid"
"type.builtin" = "cyberflare"

variable = "glitch_blossom"
"variable.builtin" = { fg = "pixelated_petal", modifiers = ["bold"] }
"variable.other.member" = "stackwave"
"variable.parameter" = "coolbit"

[palette]
ambertrace = "#F0BB6B"
ambertrace_overclocked = "#EBA63D"
cachelight = "#E7D5A4"
coldboot = "#3960D0"
coolbit = "#8ECBD6"
cyberflare = "#F78C6C"
darknet = "#1F172B"
darknet_echoed = "#261C35"
darknet_softwired = "#2E223F"
dreamware = "#A477BE"
dreamware_echoed = "#BA97CE"
dreamware_overclocked = "#8B60A4"
ghost_print = "#CAAEEB"
glitch_blossom = "#DF84A2"
low_signal = "#524168"
mintcore = "#40CFCF"
neon_orchid = "#BD4C9F"
neuroshade = "#5FE09F"
pixelated_petal = "#E29FA4"
redshift = "#F07C7C"
# shell_dust = "#3D3D3D"
# shell_dust_echoed = "#575757"
solarbyte = "#F1B718"
stackwave = "#5C7FE2"
synthetic_bleed = "#E85462"
sys_ready = "#4CA779"
sys_ready_echoed = "#6CBC93"
tech_hazard = "#D8FC4A"

test_red = "#FF0000"
