# Alternight theme for Helix
# Author: Mauricio Paternina<hi@mau.sh>
# Upstream: https://github.com/alternight-theme/helix
# Contributing
#   Please submit your changes to the upstream above.
#   The Alternight team will update the repo, including you as a co-author.

"ui.background" = { bg = "darknet" }
"ui.background.separator" = { bg = "darknet" }

"ui.cursor" = { bg = "tech_hazard", fg = "darknet", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "tech_hazard", fg = "darknet", modifiers = ["bold"] }
"ui.cursor.primary" = { bg = "tech_hazard", fg = "darknet" }

# "ui.cursorline.primary" = { bg = "test_red" }

"ui.linenr" = "low_signal"
"ui.linenr.selected" = { fg = "ghost_print" }

# TODO: Update selection bg color
"ui.selection" = { fg = "darknet", bg = "low_signal" }

"ui.statusline" = { fg = "ghost_print", bg = "darknet_light" }
"ui.statusline.inactive" = { bg = "#D8959A", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "tech_hazard", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.normal" = { bg = "glitch_blossom", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "stackwave", fg = "darknet", modifiers = ["bold"] }

"ui.text" = "ghost_print"

"ui.virtual.indent-guide" = "darknet_hardwired"

# TODO: "diagnostic.error" = { fg = "#E85462", bg = "#FADBDE", underline = { color = "#E85462", style = "curl" } }

"diff.minus" = "redshift"
"diff.plus" = "sys_ready"

error = "synthetic_bleed"
hint = "coolbit"
info = "stackwave"
warning = "solarbyte"

# Syntax
# TODO: attribute
comment = "low_signal"
constant = "solarbyte"

function = "cachelight"
# TODO: "function.macro" = "TBD"
"function.builtin" = "cachelight"

keyword = "dreamware"
"keyword.directive" = "dreamware_overclocked"

markup = "dreamware_overclocked"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "pixelated_petal"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "stackwave"
"markup.link.url" = "coldboot"
"markup.quote" = { fg = "pixelated_petal", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

namespace = { fg = "dreamware_echoed", modifiers = ["bold"] }

string = "sys_ready"
"string.regexp" = "cachelight"
"string.special" = "test_red"

type = "ambertrace"
"type.builtin" = "ambertrace_overclocked"

variable = "glitch_blossom"
"variable.builtin" = { fg = "pixelated_petal", modifiers = ["bold"] }
"variable.parameter" = "coolbit"

[palette]
ambertrace = "#F0BB6B"
ambertrace_overclocked = "#EBA63D"
cachelight = "#E7D5A4"
coldboot = "#3960D0"
coolbit = "#8ECBD6"
cyberflare = "#F78C6C"
darknet = "#1F172B"
darknet_dark = "#07050A"
darknet_hardwired = "#2E223F"
darknet_light = "#37294C"
dreamware = "#A477BE"
dreamware_echoed = "#BA97CE"
dreamware_overclocked = "#8B60A4"
ghost_print = "#CAAEEB"
glitch_blossom = "#DF84A2"
low_signal = "#524168"
pixelated_petal = "#E29FA4"
redshift = "#F07C7C"
# shell_dust = "#3D3D3D"
# shell_dust_echoed = "#575757"
solarbyte = "#F1B718"
stackwave = "#5C7FE2"
synthetic_bleed = "#E85462"
sys_ready = "#4CA779"
tech_hazard = "#D8FC4A"

test_red = "#FF0000"
