# AlterNight theme for Helix
# Author: Mauricio Paternina<hi@mau.sh>
# Upstream: https://github.com/alternight-theme/helix
# Contributing
#   Please submit your changes to the upstream above.
#   I will review them and update the repo, including you as a co-author.

"ui.background" = { bg = "darknet" }
"ui.background.separator" = { bg = "darknet" }

"ui.bufferline" = { bg = "darknet_echoed", fg = "ghost_print" }
"ui.bufferline.active" = { bg = "pixelated_petal", fg = "darknet" }

"ui.cursor" = { bg = "irradiant", fg = "darknet", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "irradiant_overclocked", fg = "darknet", modifiers = ["bold"] }
"ui.cursor.primary" = { bg = "irradiant", fg = "darknet" }

# "ui.cursorline.primary" = { bg = "test_red" }

"ui.help" = { bg = "dreamware", fg = "darknet" }

"ui.linenr" = "low_signal"
"ui.linenr.selected" = { fg = "ghost_print" }

"ui.menu" = { bg = "darknet_softwired", fg = "ghost_print" }
"ui.menu.selected" = { bg = "ghost_print", fg = "darknet" }

"ui.popup" = { bg = "darknet_echoed", fg = "ghost_print" }

"ui.selection" = { fg = "darknet", bg = "irradiant_hardwired" }

"ui.statusline" = { fg = "ghost_print", bg = "darknet_softwired" }
"ui.statusline.inactive" = { bg = "#D8959A", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "irradiant", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.normal" = { bg = "pixelated_petal", fg = "darknet", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "stackwave", fg = "darknet", modifiers = ["bold"] }

"ui.text" = "ghost_print"

"ui.virtual.indent-guide" = "darknet_softwired"

"ui.window" = { bg = "test_red" }

error = { fg = "synthetic_bleed", bg = "pixelated_petal_softwired", underline = { color = "synthetic_bleed", style = "curl" } }
# error = "synthetic_bleed"
hint = "mintcore_echoed"
info = "stackwave"
warning = "cachelight_hardwired"

# Syntax
attribute = { fg = "pixelated_petal_echoed", modifiers = ["italic"] }

comment = "low_signal"

constant = "cachelight_hardwired"
# TODO: "constant.builtin"
"constant.character" = "sys_ready_softwired"
"constant.character.escape" = "mintcore"
"constant.numeric" = "neon_orchid"

# TODO: constructor

"diagnostic.deprecated" = { fg = "voidmetal", modifiers = ["crossed_out"] }
"diagnostic.error" = { fg = "synthetic_bleed", bg = "pixelated_petal_softwired", underline = { color = "synthetic_bleed", style = "curl" } }

"diff.delta" = "mintcore_softwired"
"diff.minus" = "synthetic_bleed_overclocked"
"diff.plus" = "sys_ready_softwired"

function = "cachelight"
"function.builtin" = { fg = "cachelight", modifiers = ["bold"] }
# TODO: "function.macro"
# TODO: "function.special"

# keyword = { fg = "dreamware", modifiers = ["italic"] }
keyword = "dreamware"
"keyword.directive" = "dreamware_overclocked"

markup = "dreamware_overclocked"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "pixelated_petal"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "stackwave"
"markup.link.url" = "stackwave_overclocked"
"markup.quote" = { fg = "pixelated_petal", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

namespace = { fg = "dreamware_echoed", modifiers = ["bold"] }

string = "sys_ready"
"string.regexp" = "neon_orchid"
# TODO: Use green from neovim's
"string.special" = "sys_ready_echoed"

tag = "cyberflare"

type = "ambertrace"
# TODO: Find alternative
# "type.builtin" = "ambertrace_overclocked"
# "type.builtin" = "neon_orchid"
"type.builtin" = "cyberflare"

variable = "glitch_blossom"
"variable.builtin" = { fg = "pixelated_petal", modifiers = ["bold"] }
"variable.other.member" = "stackwave"
"variable.parameter" = "mintcore_echoed"

[palette]
ambertrace = "#F0BB6B"
ambertrace_overclocked = "#EBA63D"
cachelight = "#E7D5A4"
cachelight_hardwired = "#F1B718"
cyberflare = "#F78C6C"
darknet = "#1F172B"
darknet_echoed = "#261C35"
darknet_softwired = "#2E223F"
dreamware = "#A477BE"
dreamware_echoed = "#BA97CE"
dreamware_overclocked = "#8B60A4"
ghost_print = "#CAAEEB"
glitch_blossom = "#DF84A2"
irradiant = "#D8FC4A"
irradiant_hardwired = "#718C02"
irradiant_overclocked = "#B1DD04"
low_signal = "#524168"
mintcore = "#40CFCF"
mintcore_echoed = "#8ECBD6"
mintcore_softwired = "#B4DDE4"
neon_orchid = "#BD4C9F"
pixelated_petal = "#E29FA4"
pixelated_petal_echoed = "#E4BABA"
pixelated_petal_softwired = "#FADBDE"
stackwave = "#5C7FE2"
stackwave_overclocked = "#3960D0"
synthetic_bleed = "#E85462"
synthetic_bleed_overclocked = "#E64252"
sys_ready = "#4CA779"
sys_ready_echoed = "#6CBC93"
sys_ready_softwired = "#5FE09F"
voidmetal = "#78767F"

test_red = "#FF0000"
